import type { Metadata } from 'next'

import Footer from '@/components/footer'
import MainLayout from '@/components/layouts/main-layout'
import Navbar from '@/components/navbar'
import ProgresBarTop from '@/components/progres-bar-top'
import TanstackQueryProvider from '@/components/tanstack-query-provider'
import { ThemeProvider } from '@/components/theme-provider'
import { inter } from '@/lib/fonts'
import { cn } from '@/lib/utils'
import { Toaster } from 'sonner'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body className={cn('relative h-full antialiased', inter.variable)}>
        <TanstackQueryProvider>
          <ThemeProvider attribute="class" defaultTheme="system">
            <main className="relative flex min-h-screen flex-col">
              <ProgresBarTop>
                <Toaster expand={true} richColors position="top-right" />
                {children}
              </ProgresBarTop>
            </main>
          </ThemeProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  )
}
